# Generated by Django 5.1.4 on 2025-01-10 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0003_alter_blogpost_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='description',
            new_name='content',
        ),
    ]
